### ISSUE TITLE
Tuning PID controllers

### ISSUE THREAD

**Issue by f-jiang** [rayvburn/diff_drive_mapping_robot#1]
I'm not sure if this is the right place to be asking, but I have a robot similar to yours with the `diff_drive_controller` and `pid` nodes organized the exact same way. I'm currently at the stage of tuning my PID controllers and wanted to understand the best approach to doing so. Did you tune your PIDs in a simulator, and how did you set things up?

**Comment by rayvburn** [comment]
Sorry for a late reply. 

Whole testing process was conducted on the real robot. To tune the PID params I used a trial and error method, starting from a set of verified settings from some example.
